setwd("D:/GIT/R-code-for-multivariate-analysis")
source("biostats.R")
install.packages("simba")
install.packages("vegan")
install.packages("ecodist")
install.packages("cluster")
library("simba")
library("vegan")
library("ecodist")
library("cluster")

envdata<-read.csv('MAHA_environment.csv', header = TRUE, row.names = 1)
speabu <- read.csv('MAHA_speciesabu.csv', header=TRUE, row.names = 1)
spetrait<-read.csv('MAHA_speciestrait.csv', header=TRUE, row.names=1)
